#!/bin/sh

REPO_ROOT=$(git rev-parse --show-toplevel)
ESLINT_PATH="Behavioral-Patterns/frontend/node_modules/.bin/eslint"

cd "$REPO_ROOT"

if [ ! -x "$ESLINT_PATH" ]; then
  echo -e "\033[41mESLint not installed\033[0m"
  exit 1
fi

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")

echo "Linting ${#STAGED_FILES} files"

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

"${ESLINT_PATH}" "${STAGED_FILES[@]}"

ESLINT_EXIT=$?

git add "${STAGED_FILES[@]}"

if [ $ESLINT_EXIT -eq 0 ]; then
  echo "\033[42mOK\033[0m"
else
  echo "\033[41m FAIL \033[0m"
  exit 1
fi

exit $?
